spring:
  data.mongodb:
    database: products                 # Database name.
    address: 129.156.113.125          # mongodb address
    uri: mongodb://${spring.data.mongodb.address}:27017    # Mongo database URI. Cannot be set with host, port and credentials.
  
  kafka:
#    bootstrap-servers: localhost:9092
#    bootstrap-servers: 129.150.114.134:9092
    bootstrap-servers: 129.156.113.171:6667
    kafka.acks: all
    retries: 0
    consumer:
      auto-offset-reset: latest
      group-id: product-group  
#    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    schema-registry-url: http://129.156.113.125:8081

  jackson.serialization.indent_output: true
  
kafka:
  topic:
    addToShoppingCart: idcs-1d61df536acb4e9d929e79a92f3414b5-soaringaddtoshoppingcart
    product: idcs-1d61df536acb4e9d929e79a92f3414b5-soaringproducts
#    product: product